config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :enrollments
  resources :courses
  resources :admins
  resources :students
  resources :instructors
  devise_for :users
  get 'home/index'
  root 'home#index'
  get '/enroll_course/:id' , to: 'enrollments#enroll_course', as: 'enroll_course'
  get '/about_us' , to: 'home#about_us', as: 'about_us'
  get '/waitlist_course/:id' , to: 'waitlists#waitlist_course', as: 'waitlist_course'
  get '/instructor_courses' , to: 'courses#instructor_courses', as: 'instructor_courses'
  get '/courses/:id/enrolled_students' , to: 'courses#enrolled_students', as: 'enrolled_students'
  get '/courses/:id/waitlisted_students' , to: 'courses#waitlisted_students', as: 'waitlisted_students'
  get '/courses/:course_id/enroll_course_for_student/', to: 'enrollments#show_enroll_course_for_student', as: 'show_enroll_course_for_student'
  get '/courses/:course_id/waitlist_course_for_student/', to: 'waitlists#show_waitlist_course_for_student', as: 'show_waitlist_course_for_student'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/waitlist.rb
class Waitlist < ApplicationRecord
  belongs_to :student
  belongs_to :course
  validates :student_id, :uniqueness => {:scope => :course_id, :message => "You have already waitlisted for this course."}
end

app/controllers/waitlists_controller.rb
class WaitlistsController < ApplicationController
  before_action :set_waitlist, only: %i[ show edit update destroy ]
  before_action :correct_student?, only: %i[ edit update destroy show ]
  before_action :correct_instructor?, only: %i[ edit update destroy show create ]

  # GET /waitlists or /waitlists.json
  def index
    if is_student?
      # this shows waitlists for the current user
      @waitlists = Waitlist.where(student_id: Student.find_by(user_id: current_user.id).id)
    elsif is_instructor?
      # blocks access to instructor as he can see from the courses details page
      flash[:alert] = "Not authorised to perform this action"
      redirect_to courses_path
    elsif is_admin?
      #  this shows all the waitlists for all students
      @waitlists = Waitlist.all
    end
  end

  # GET /waitlists/1 or /waitlists/1.json
  def show
  end

  # GET /waitlists/new
  def new
    @waitlist = Waitlist.new
  end

  # GET /waitlists/1/edit
  def edit
    flash[:alert] = "Not authorised to perform this action"
    redirect_to courses_path
  end

  # POST /waitlists or /waitlists.json
  def create
    waitlist_course
    respond_to do |format|
      if @waitlist.save
        @course = Course.find(@waitlist.course_id)
        check_status
        format.html { redirect_to waitlisted_students_path(@course.id), notice: "Waitlist was successfully created." }
        format.json { render :show, status: :created, location: @waitlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json:{}, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waitlists/1 or /waitlists/1.json
  def update
    respond_to do |format|
      if @waitlist.update(waitlist_params)
        @course = Course.find(@waitlist.course_id)
        check_status
        format.html { redirect_to waitlist_url(@waitlist), notice: "Waitlist was successfully updated." }
        format.json { render :show, status: :ok, location: @waitlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json:  @waitlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waitlists/1 or /waitlists/1.json
  def destroy
    @course = Course.find(@waitlist.course_id)
    @waitlist.destroy
    check_status
    respond_to do |format|

      if is_instructor?
        format.html { redirect_to waitlisted_students_url(@waitlist.course_id), alert: "Waitlist for #{@course.name} is dropped." }
      elsif flash[:controller_from] == "Course"
        format.html { redirect_to courses_path, alert: "Waitlist for #{@course.name} is dropped." }
      else
        format.html { redirect_to waitlists_url, alert: "Waitlist for #{@course.name} is dropped." }
      end

      format.json { head :no_content }
    end
  end

  # this will check the status for a course and modify it based on the number of enrollments and waitlists
  # it considers the course waitlist_capacity and the capacity to dermine the status of the course
  def check_status
    total_enrollments = Enrollment.where(course_id: @course.id).count
    total_waitlist = Waitlist.where(course_id: @course.id).count
    if total_enrollments >= @course.capacity
      if total_waitlist >= @course.waitlist_capacity
        @course.status = :closed
      else
        @course.status = :waitlist
      end
    elsif total_enrollments < @course.capacity && (@course.status == "closed" || @course.status == "waitlist")
      @course.status = :open
    end
    @course.save
  end


  #  GET /waitlist_course/:id or /waitlist_course/1
  # this is for a student to waitlist a course
  def waitlist_course
    @waitlist = Waitlist.new

    if !is_student? && (!waitlist_params[:course_id] || !waitlist_params[:student_id])
      flash[:alert] = "course and student should not be empty"
      return
    end
    if is_student?
      @course = Course.find(params[:id])
      @student = Student.find_by user_id: current_user.id
    else
      @course = Course.find(waitlist_params[:course_id])
      @student = Student.find waitlist_params[:student_id]
    end

    total_waitlist = Waitlist.where(course_id: @course.id).count
    total_enrollment = Enrollment.where(course_id: @course.id).count
    if @course.capacity > total_enrollment
      flash[:alert] = "Enrollment is still open for the course please go to enrollments to enroll for the course"
    elsif Enrollment.find_by(student_id: @student.id, course_id: @course.id)
      flash[:alert] = "Student is already enrolled for this course"
    elsif Waitlist.find_by(student_id: @student.id, course_id: @course.id)
      flash[:alert] = "Student is already waitlisted for this course"
    elsif @course.status == "waitlist" && @course.waitlist_capacity > total_waitlist and @student != nil
      @waitlist.student_id = @student.id
      @waitlist.course_id = @course.id
      if is_student?
        flash[:alert] = "Successfully waitlisted for the course #{@course.name}"
        @waitlist.save
      end
      check_status
    elsif @course.waitlist_capacity <= total_waitlist
      flash[:alert] = "Course status is closed, please keep checking MyBiryaniPack protal when it opens up."
    end
    if is_student?
      redirect_to courses_path
    end
  end

  # /courses/:id/waitlisted_students 
  # shows all students waitlist in the course passed as arguemnt
  # this is visible by admin and authorized instructor
  def show_waitlist_course_for_student
    @waitlist = Waitlist.new
    @course = Course.find params[:course_id]
    render :new
  end

  # this will block operations that student should not access
  def correct_student?
    @student = Student.find_by user_id: current_user.id
    if !@student.nil? && @student.id!=@waitlist.student_id
       flash[:alert] = "Not authorised to perform this action"
       redirect_to root_path
    end
  end

  # this will block operations that instructor should not access
  # it will block the instructor if the course whose enrollments are not belongging to his/her course
  def correct_instructor?
    if is_instructor?
      @instructor = Instructor.find_by user_id: current_user.id
      course_instructor_id = 0
      if @waitlist
        course_instructor_id = @waitlist.course.instructor.id
      else
        course_instructor_id = Course.find(waitlist_params[:course_id]).instructor.id
      end
      if !@instructor.nil? && @instructor.id!=course_instructor_id
        flash[:alert] = "Not authorised to perform this action"
        redirect_to root_path
      end
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waitlist
      @waitlist = Waitlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def waitlist_params
      params.require(:waitlist).permit(:student_id, :course_id)
    end
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/views/waitlists/_form.html.erb
<%= form_with(model: waitlist) do |form| %>
  <div class="form-group">
    <%= form.label :student_id %>
        <% if @course  %>
      <%= form.select :student_id, options_for_select(Student.where.not(id: Waitlist.where(course_id: @course.id).map{|s| s.student_id}.compact).map{|stu| [stu.user.name, stu.id]}) ,{}, {include_blank: false, class:"form-control"}%>
        <% else %>
      <%= form.select :student_id, options_for_select(Student.all.map{|stu| [stu.user.name, stu.id]}) ,{}, {include_blank: false, class:"form-control"}%>
        <% end %>
  </div>
  
  <div class="form-group">
    <%= form.label :course_id %>
    <% if @course  %>
      <%= form.text_field :course_id, value: @course.id, readonly: true, class:"form-control"%>
    <% else %>
          <%= form.select :course_id, options_for_select(Course.all.map{|c| [c.name, c.id]}) ,{}, {include_blank: false, class:"form-control"}%>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/waitlists/edit.html.erb
<h1>Editing Waitlist</h1>

<%= render 'form', waitlist: @waitlist %>

<%= link_to 'Show', @waitlist , class: 'btn btn-primary' %> |
<%= link_to 'Back', waitlists_path , class: 'btn btn-primary' %>

app/views/waitlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Waitlists</h1>

<% if is_admin? %>
<%= link_to 'New Waitlist', new_waitlist_path , class: 'btn btn-primary' %>
<%end%>
<%= link_to 'Back', home_index_path , class: 'btn btn-primary' %>


<table class="table">
  <thead>
    <tr>
      <th>Student Name</th>
      <th>Course Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waitlists.each do |waitlist| %>
      <tr>
      <td><%= link_to waitlist.student.user.name , student_url(waitlist.student) %></td>
        <td><%= link_to waitlist.course.name , course_url(waitlist.course) %></td>
        <td><%= link_to 'Drop Waitlist', waitlist, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger btn-sm'%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/waitlists/new.html.erb
<h1>New Waitlist</h1>

<%= render 'form', waitlist: @waitlist %>

<%= link_to 'Back', waitlists_path , class: 'btn btn-primary' %>

app/views/waitlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @waitlist.student_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @waitlist.course_id %>
</p>

<%= link_to 'Edit', edit_waitlist_path(@waitlist) , class: 'btn btn-primary' %> |
<%= link_to 'Back', waitlists_path , class: 'btn btn-primary' %>