config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :enrollments
  resources :courses
  resources :admins
  resources :students
  resources :instructors
  devise_for :users
  get 'home/index'
  root 'home#index'
  get '/enroll_course/:id' , to: 'enrollments#enroll_course', as: 'enroll_course'
  get '/about_us' , to: 'home#about_us', as: 'about_us'
  get '/waitlist_course/:id' , to: 'waitlists#waitlist_course', as: 'waitlist_course'
  get '/instructor_courses' , to: 'courses#instructor_courses', as: 'instructor_courses'
  get '/courses/:id/enrolled_students' , to: 'courses#enrolled_students', as: 'enrolled_students'
  get '/courses/:id/waitlisted_students' , to: 'courses#waitlisted_students', as: 'waitlisted_students'
  get '/courses/:course_id/enroll_course_for_student/', to: 'enrollments#show_enroll_course_for_student', as: 'show_enroll_course_for_student'
  get '/courses/:course_id/waitlist_course_for_student/', to: 'waitlists#show_waitlist_course_for_student', as: 'show_waitlist_course_for_student'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #index page
  def index
    #check if the current logged in user is an instructor or not
    if is_instructor?
      if !Instructor.exists?(user_id:current_user.id)
        inst = Instructor.new
        inst.user_id = current_user.id
        inst.department = 'edit deptartment'
        inst.save!
        p inst
        redirect_to edit_instructor_path :id=>inst.id
      end
    end

    #check if the current logged in user is a student or not
    if is_student?
      if !Student.exists?(user_id:current_user.id)
        stud = Student.new
        stud.user_id = current_user.id
        stud.phone_number = 'Edit Phone'
        stud.date_of_birth = Date.current
        stud.major = 'Edit Major'
        stud.save!
        p stud
        redirect_to edit_student_path :id=>stud.id
      end
    end


  end

  # GET /about_us
  # shows the fancy about page
  def about_us
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'MyBiryaniPack', root_path, class:"navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
              <%= link_to 'Courses', courses_path, class:"nav-link"  %>
            </li>
            <% if is_admin?%>
              <li class="nav-item">
                <%= link_to 'Instructors', instructors_path, class:"nav-link"  %>
              </li>
              <li class="nav-item">
                <%= link_to 'Students', students_path, class:"nav-link"  %>
              </li>
            <% end %>
            <% if !is_instructor?%>

              <li class="nav-item">
                <%= link_to 'Enrollments', enrollments_path, class:"nav-link"  %>
              </li>
              <li class="nav-item">
                <%= link_to 'Waitlists', waitlists_path, class:"nav-link"  %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to 'About Us', about_us_path, class:"nav-link"  %>
            </li>
        </ul>
        <ul class="navbar-nav d-flex">
          <% if user_signed_in? %>
            <li class="nav-item">
              <div class="nav-link" ><%=  current_user.name%></div>
            </li>
            <li class="nav-item">
              <div class="nav-link" >Role: <% if is_student?%><b>Student</b> <%elsif is_instructor? %> <b><i>Instructor</i></b><%elsif is_admin?%> <u>Admin</u> <%end%></div>
            </li>
            <li class="nav-item">
              <%= link_to 'Edit Profile',edit_user_registration_path , class:"nav-link"  %>
            </li>
            <li class="nav-item">
                <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"nav-link"  %>
            </li>
          <% else %>
            <li class="nav-item">
                <%= link_to 'Login', new_user_session_path, class:"nav-link"  %>
            </li>
            <li class="nav-item">
                <%= link_to 'Register', new_user_registration_path, class:"nav-link"  %>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/home/about_us.html.erb
<style>
.container {
  height: 100vh;
  width: 100vw;
  max-height: 800px;
  max-width: 1280px;
  min-height: 600px;
  min-width: 1000px;
  display: flex;
  justify-content: space-around;
  align-items: center;
  margin: 0 auto;
}
.border {
  height: 369px;
  width: 290px;
  background: transparent;
  border-radius: 10px;
  transition: border 1s;
  position: relative;
}
.border:hover {
  border: 1px solid #fff;
}
.card {
  height: 379px;
  width: 300px;
  background: #808080;
  border-radius: 10px;
  transition: background 0.8s;
  overflow: hidden;
  background: #000;
  box-shadow: 0 70px 63px -60px #000;
  display: flex;
  justify-content: center;
  align-items: center;
  position: relative;
}
.card0 {
  background: url(/assets/SaurabhKrishna-1ad44851a21a633d6469acc55ec07611fba8eaad1cdfb9a2772e33195f515f5c.JPG) center center no-repeat;
  background-size: 300px;
}
.card0:hover {
  background: url(/assets/SaurabhKrishna-1ad44851a21a633d6469acc55ec07611fba8eaad1cdfb9a2772e33195f515f5c.JPG) left center no-repeat;
  background-size: 600px;
}
.card0:hover h2 {
  opacity: 1;
}
.card0:hover .fa {
  opacity: 1;
}
.card1 {
  background: url(/assets/22720-cde832c4a666303c62f72769e7ef48b3753f463cf1937c18db95a4b7abdff8f6.jpg) center center no-repeat;
  background-size: 300px;
}
.card1:hover {
  background: url(/assets/22720-cde832c4a666303c62f72769e7ef48b3753f463cf1937c18db95a4b7abdff8f6.jpg) left center no-repeat;
  background-size: 600px;
}
.card1:hover h2 {
  opacity: 1;
}
.card1:hover .fa {
  opacity: 1;
}
.card2 {
  background: url(/assets/prasanna-2aafa046f2d3d4d012a1a5e728b90fc385620f56805e2dc2ad9180adac250246.png) center center no-repeat;
  background-size: 300px;
}
.card2:hover {
  background: url(/assets/prasanna-2aafa046f2d3d4d012a1a5e728b90fc385620f56805e2dc2ad9180adac250246.png) left center no-repeat;
  background-size: 600px;
}
.card2:hover h2 {
  opacity: 1;
}
.card2:hover .fa {
  opacity: 1;
}
h2 {
  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
  color: #fff;
  margin: 20px;
  opacity: 0;
  transition: opacity 1s;
}
.fa {
  opacity: 0;
  transition: opacity 1s;
}
.icons {
  position: absolute;
  fill: #fff;
  color: #fff;
  height: 130px;
  top: 226px;
  width: 50px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-around;
}

</style>

<div class="container">
  <div class="card card0">
    <a href="https://www.linkedin.com/in/krishnasaurabh/">
      <div class="border">
        <h2>Krishna Saurabh Vankadaru</h2>
        <div class="icons">
          <i class="fa fa-codepen" aria-hidden="true"></i>
          <i class="fa fa-instagram" aria-hidden="true"></i>
          <i class="fa fa-dribbble" aria-hidden="true"></i>
          <i class="fa fa-twitter" aria-hidden="true"></i>
          <i class="fa fa-facebook" aria-hidden="true"></i>
        </div>
      </div>
    </a>
  </div>
  <div class="card card1">
  <a href="https://www.linkedin.com/in/atharva-r-patil/">
    <div class="border">
      <h2>Atharva Patil</h2>
      <div class="icons">
        <i class="fa fa-codepen" aria-hidden="true"></i>
        <i class="fa fa-instagram" aria-hidden="true"></i>
        <i class="fa fa-dribbble" aria-hidden="true"></i>
        <i class="fa fa-twitter" aria-hidden="true"></i>
        <i class="fa fa-facebook" aria-hidden="true"></i>
      </div>
    </div>
    </a>
  </div>
  <div class="card card2">
  <a href="https://www.linkedin.com/in/krishna-prasanna-bhamidipati/">
    <div class="border">
      <h2>Krishna Prasanna Bhamidipati</h2>
      <div class="icons">
        <i class="fa fa-codepen" aria-hidden="true"></i>
        <i class="fa fa-instagram" aria-hidden="true"></i>
        <i class="fa fa-dribbble" aria-hidden="true"></i>
        <i class="fa fa-twitter" aria-hidden="true"></i>
        <i class="fa fa-facebook" aria-hidden="true"></i>
      </div>
    </div>
    </a>
  </div>
</div>

app/views/home/index.html.erb
<style>
.card {
  background-color: #fff;
  border-radius: 4px;
  max-width: 400px;
  height: 100px;
  position: relative;
  padding: 34px;
  color: #444;
  cursor: pointer;
}
.card:before {
  content: "";
  display: block;
  position: absolute;
  background-color: #ccc;
  left: 20px;
  right: 20px;
  bottom: 0;
  top: 50%;
  z-index: -1;
  box-shadow: 0 0 40px #999999;
  transition: box-shadow 0.2s ease-in-out;
}
.card.level-3:hover:before {
  box-shadow: 0 0 80px #999999;
}
.card h5 {
  font-weight: 300;
  font-size: 30px;
}

</style>
<% if is_instructor? %> 
    <h2>Hello Instructor <%= current_user.name %></h2>

    <%= link_to  courses_path, class: 'card level-3' do%> 
    <h5>All Courses</h5>
    <%end%>

<br/>
    <%= link_to  instructor_courses_path, class: 'card level-3' do%> 
    <h5>My Courses</h5>
    <%end%>
<br/>
    <%= link_to  edit_instructor_path(get_cur_instructor), class: 'card level-3' do%> 
    <h5>Edit Profile</h5>
<%end%>
<br/>
    <%= link_to  instructor_path(get_cur_instructor), class: 'card level-3' do%> 
    <h5>My Profile</h5>
<%end%>


<% elsif is_student? %>
    <h2>Welcome, <%=current_user.name %></h2>
    <p>Following are the actions you are allowed to perform:</p>
    
    <%= link_to  courses_path, class: 'card level-3' do%> 
    <h5>Courses</h5>
    <%end%>
<br/>
    <%= link_to  enrollments_path, class: 'card level-3' do%> 
    <h5>My Enrollments</h5>
    <%end%>
<br/>
    <%= link_to  waitlists_path, class: 'card level-3' do%> 
    <h5>My Waitlists</h5>
    <%end%>
<br/>
    <%= link_to  edit_student_path(get_cur_student), class: 'card level-3' do%> 
    <h5>Edit Profile</h5>
    <%end%>
<br/>
    <%= link_to  student_path(get_cur_student), class: 'card level-3' do%> 
    <h5>My Profile</h5>
    <%end%>

<br/>

<% else %>
    <h1>Hi Admin <%= current_user.name %></h1>
        <%= link_to  courses_path, class: 'card level-3' do%> 
    <h5>Courses</h5>
    <%end%>
<br/>
    <%= link_to  enrollments_path, class: 'card level-3' do%> 
    <h5>Enrollments</h5>
    <%end%>
<br/>
    <%= link_to  waitlists_path, class: 'card level-3' do%> 
    <h5>Waitlists</h5>
    <%end%>
<br/>
    <%= link_to  students_path, class: 'card level-3' do%> 
    <h5>Students</h5>
    <%end%>
<br/>
    <%= link_to  instructors_path, class: 'card level-3' do%> 
    <h5>Instructors</h5>
    <%end%>
<br/>
    <%= link_to  edit_user_registration_path, class: 'card level-3' do%> 
    <h5>Edit Profile</h5>
    <%end%>
<br/>
<% end %>