config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :enrollments
  resources :courses
  resources :admins
  resources :students
  resources :instructors
  devise_for :users
  get 'home/index'
  root 'home#index'
  get '/enroll_course/:id' , to: 'enrollments#enroll_course', as: 'enroll_course'
  get '/about_us' , to: 'home#about_us', as: 'about_us'
  get '/waitlist_course/:id' , to: 'waitlists#waitlist_course', as: 'waitlist_course'
  get '/instructor_courses' , to: 'courses#instructor_courses', as: 'instructor_courses'
  get '/courses/:id/enrolled_students' , to: 'courses#enrolled_students', as: 'enrolled_students'
  get '/courses/:id/waitlisted_students' , to: 'courses#waitlisted_students', as: 'waitlisted_students'
  get '/courses/:course_id/enroll_course_for_student/', to: 'enrollments#show_enroll_course_for_student', as: 'show_enroll_course_for_student'
  get '/courses/:course_id/waitlist_course_for_student/', to: 'waitlists#show_waitlist_course_for_student', as: 'show_waitlist_course_for_student'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course
  validates :student_id, :uniqueness => {:scope => :course_id, :message => "You have already registered for this course."}
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]
  before_action :correct_student?, only: %i[ edit update destroy show ]
  before_action :correct_instructor?, only: %i[ edit update destroy show create ]


  # GET /enrollments or /enrollments.json
  def index
    if is_student?
      # this shows enrollments for the current user
      @enrollments = Enrollment.where(student_id: Student.find_by(user_id: current_user.id).id)
    elsif is_instructor?
      # blocks access to instructor as he can see from the courses details page
      flash[:alert] = "Not authorised to perform this action"
      redirect_to courses_path
    elsif is_admin?
      #  this shows all the enrollemets for all students
      @enrollments = Enrollment.all
    end
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit 
  # all edit operations are not authorized it can only be deleted or created
  def edit
    flash[:alert] = "Not authorised to perform this action"
    redirect_to root_path
  end

  # POST /enrollments or /enrollments.json
  def create
    enroll_course
    respond_to do |format|
      if @enrollment.save
        @course = Course.find(@enrollment.course_id)
        check_status
        format.html { redirect_to enrolled_students_path(@course.id), alert: "Enrollment was successfully created." }
        format.json { render :enrolled_students_path, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        @course = Course.find(@enrollment.course_id)
        check_status
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @course = Course.find(@enrollment.course_id)
    @enrollment.destroy
    move_students_from_waitlist_to_enrolled 
    check_status 
    respond_to do |format|
      if is_instructor?
        format.html { redirect_to enrolled_students_url(@enrollment.course_id), alert: "Enrollment for #{@course.name} is dropped." }
      elsif flash[:controller_from] == "Course"
        format.html { redirect_to courses_path, alert: "Enrollment for #{@course.name} is dropped." }
      else
        format.html { redirect_to enrollments_url, alert: "Enrollment for #{@course.name} is dropped." }
      end
      format.json { head :no_content }
    end
  end

  #  GET /waitlist_course/:id or /waitlist_course/1
  # this is for a student to waitlist a course
  def enroll_course
    @enrollment = Enrollment.new
    if !is_student? && (!enrollment_params[:course_id] || !enrollment_params[:student_id])
      flash[:alert] = "course and student should not be empty"
      return
    end
    if is_student?
      @course = Course.find(params[:id])
      @student = Student.find_by user_id: current_user.id
    else
      @course = Course.find(enrollment_params[:course_id])
      @student = Student.find enrollment_params[:student_id]
    end

    total_waitlist = Waitlist.where(course_id: @course.id).count
    total_enrollment = Enrollment.where(course_id: @course.id).count
    
    if Enrollment.find_by(student_id: @student.id, course_id: @course.id)
      flash[:alert] = "Student is already registered for this course"
    elsif @course.capacity > total_enrollment and @student != nil
      @enrollment.student_id = @student.id 
      @enrollment.course_id = @course.id
      if is_student?
        flash[:alert] = "Successfully enrolled for the course #{@course.name}"
        @enrollment.save
      end
      check_status
    elsif @course.capacity <= total_enrollment
      if @course.status == 'closed'
        flash[:alert] = "Course status is closed, please keep checking MyBiryaniPack protal when it opens up."
      elsif @course.status == 'waitlist'
        flash[:alert] = "Course status is waitlist, please click waitlist if you want to get added to the course waitlist."
      end
    end

    if is_student?
      redirect_to courses_path
    end
  end

  # /courses/:id/enrolled_students 
  # shows all students enrolled in the course passed as arguemnt
  # this is visible by admin and authorized instructor
  def show_enroll_course_for_student
    @enrollment = Enrollment.new
    @course = Course.find params[:course_id]
    render :new
  end

  # this is triggered when an enrollment is dropped to move students from waitlist to enrollments 
  # the top waitlist for that course (having least created_at) is converted to enrollment
  def move_students_from_waitlist_to_enrolled
    total_enrollments = Enrollment.where(course_id: @course.id).count
    total_waitlist = Waitlist.where(course_id: @course.id).count

    if total_enrollments < @course.capacity && total_waitlist > 0
      student_to_be_enrolled = Waitlist.where(course_id: @course.id).order("created_at ASC").first
      enrolled_student = Enrollment.create!(:student_id => student_to_be_enrolled.student_id , :course_id => student_to_be_enrolled.course_id)
      student_to_be_enrolled.destroy
    end
  end

  # this will check the status for a course and modify it based on the number of enrollments and waitlists
  # it considers the course waitlist_capacity and the capacity to dermine the status of the course
  def check_status
    total_enrollments = Enrollment.where(course_id: @course.id).count
    total_waitlist = Waitlist.where(course_id: @course.id).count
    
    if total_enrollments >= @course.capacity
      if total_waitlist >= @course.waitlist_capacity
        @course.status = :closed
      else
        @course.status = :waitlist
      end
    elsif total_enrollments < @course.capacity && (@course.status == "closed" || @course.status == "waitlist")
      @course.status = :open
    end
    @course.save
  end

  # this will block operations that student should not access
  def correct_student?
    @student = Student.find_by user_id: current_user.id
    if !@student.nil? && @student.id!=@enrollment.student_id
       flash[:alert] = "Not authorised to perform this action"
       redirect_to courses_path
    end
  end

  # this will block operations that instructor should not access
  # it will block the instructor if the course whose enrollments are not belongging to his/her course
  def correct_instructor?
    if is_instructor?
      @instructor = Instructor.find_by user_id: current_user.id
      course_instructor_id = 0
      if @enrollment
        course_instructor_id = @enrollment.course.instructor.id
      else
        course_instructor_id = Course.find(enrollment_params[:course_id]).instructor.id
      end
      if !@instructor.nil? && @instructor.id != course_instructor_id
        flash[:alert] = "Not authorised to perform this action"
        redirect_to root_path
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:student_id, :course_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment) do |form| %>


  <div class="form-group">
    <%= form.label :student_id %>
        <% if @course  %>
      <%= form.select :student_id, options_for_select(Student.where.not(id: Enrollment.where(course_id: @course.id).map{|s| s.student_id}.compact).map{|stu| [stu.user.name, stu.id]}) ,{}, {include_blank: false, class:"form-control"}%>
        <% else %>
      <%= form.select :student_id, options_for_select(Student.all.map{|stu| [stu.user.name, stu.id]}) ,{}, {include_blank: false, class:"form-control"}%>
        <% end %>
  </div>
  
  <div class="form-group">
    <%= form.label :course_id %>
    <% if @course  %>
      <%= form.text_field :course_id, value: @course.id, readonly: true, class:"form-control"%>
    <% else %>
          <%= form.select :course_id, options_for_select(Course.all.map{|c| [c.name, c.id]}) ,{}, {include_blank: false, class:"form-control"}%>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Show', @enrollment , class: 'btn btn-primary' %> |
<%= link_to 'Back', enrollments_path , class: 'btn btn-primary' %>

app/views/enrollments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrollments</h1>

<% if !is_student? %>
<%= link_to 'New Enrollment', new_enrollment_path , class: 'btn btn-primary' %>
<%end%>
<%= link_to 'Back', home_index_path , class: 'btn btn-primary' %>

<table class="table">
  <thead>
    <tr>
      <th>Student</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= link_to enrollment.student.user.name , student_url(enrollment.student) %></td>
        <td><%= link_to enrollment.course.name , course_url(enrollment.course) %></td>
        <td><%= link_to 'Drop Enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure to drop the course?' } , class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%if @course%>
<%= link_to 'Back', enrolled_students_path(@course) , class: 'btn btn-primary' %>
<%else%>
<%= link_to 'Back', enrollments_path , class: 'btn btn-primary' %>
<%end%>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @enrollment.student_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @enrollment.course_id %>
</p>

<%= link_to 'Back', enrollments_path , class: 'btn btn-primary' %>