config/routes.rb
Rails.application.routes.draw do
  resources :waitlists
  resources :enrollments
  resources :courses
  resources :admins
  resources :students
  resources :instructors
  devise_for :users
  get 'home/index'
  root 'home#index'
  get '/enroll_course/:id' , to: 'enrollments#enroll_course', as: 'enroll_course'
  get '/about_us' , to: 'home#about_us', as: 'about_us'
  get '/waitlist_course/:id' , to: 'waitlists#waitlist_course', as: 'waitlist_course'
  get '/instructor_courses' , to: 'courses#instructor_courses', as: 'instructor_courses'
  get '/courses/:id/enrolled_students' , to: 'courses#enrolled_students', as: 'enrolled_students'
  get '/courses/:id/waitlisted_students' , to: 'courses#waitlisted_students', as: 'waitlisted_students'
  get '/courses/:course_id/enroll_course_for_student/', to: 'enrollments#show_enroll_course_for_student', as: 'show_enroll_course_for_student'
  get '/courses/:course_id/waitlist_course_for_student/', to: 'waitlists#show_waitlist_course_for_student', as: 'show_waitlist_course_for_student'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy enrolled_students waitlisted_students]
  before_action :correct_student?, only: %i[ new edit create update destroy enrolled_students waitlisted_students]
  before_action :correct_instructor?, only: %i[ edit update destroy enrolled_students waitlisted_students]

  # GET /courses or /courses.json
  #Get all the courses, if the user is an instructor, then create a var with this instructor's details pulled from db. 
  def index
    @courses = Course.all
    flash[:controller_from] = 'Course'
    if is_instructor?
      @instructor_id = Instructor.find_by(user_id: current_user.id).id
    end
  end

  #If the user is an instructor, render only courses taught by the instructor
  def instructor_courses
    @courses = Course.all
    if is_instructor?
      @instructor_id = Instructor.find_by(user_id: current_user.id).id
      @courses = Course.where instructor_id: @instructor_id
    end
    render :index
  end

  # GET /courses/1 or /courses/1.json
  #Show course
  def show
  end

  # GET /courses/new
  #Render a form to create new course.
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  #Take the course params given from UI. Check if the user is instructor, if yes, then only save these course details to db.
  def create
    @course = Course.new(course_params)
    if is_instructor?
      @instructor = Instructor.find_by user_id: current_user.id
      @course.instructor_id = @instructor.id
    end
    respond_to do |format|
      if @course.save
        check_status
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|

      if @course.update(course_params)
        fill_enrollments_with_waitlist
        check_status
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #This action checks whether the toal enrollment exceeds total capacity - if yes, then the course is closed. 
  #If the total wait-list capacity is still not met, the status is left as waitlisted instead of closed.
  #Else the status is open. This function is periodically called prior to making any changes
  def check_status
    total_enrollments = Enrollment.where(course_id: @course.id).count
    total_waitlist = Waitlist.where(course_id: @course.id).count
    
    if total_enrollments >= @course.capacity
      if total_waitlist >= @course.waitlist_capacity
        @course.status = :closed
      else
        @course.status = :waitlist
      end
    elsif total_enrollments < @course.capacity && (@course.status == "closed" || @course.status == "waitlist")
      @course.status = :open
    end
    @course.save
  end

  #An action that checks if the user is a student. If yes, block him from performing any course related modifitions. 
  def correct_student?
    @student = Student.find_by user_id: current_user.id
    if !@student.nil?
       flash[:alert] = "Not authorised to perform this action"
       redirect_to courses_path
    end
  end

#An action that checks whether the user is an instructor or not. If so, whether the course that this instructor is accessing is his own course or not. 
  def correct_instructor?
    if is_instructor?
      @instructor = Instructor.find_by user_id: current_user.id
      if @course.instructor.id!=@instructor.id
        flash[:alert] = "Not authorised to perform this action"
        redirect_to courses_path
      end
    end
  end

#Get the enrolled students if the user accessing them is an instructor or admin. 
  def enrolled_students
    if is_instructor? || is_admin?
      @course_name = Course.find(params[:id]).name
      @enrolled_students = Enrollment.where(course_id: params[:id])
    end
  end

#If the user is an isntrucro or admin, then get the waitlisted students corresponding to the course clicked on, in UI. 
  def waitlisted_students
    if is_instructor? || is_admin?
      @course_name = Course.find(params[:id]).name
      @waitlisted_students = Waitlist.where(course_id: params[:id])
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:name, :description, :weekday_one, :weekday_two, :start_time, :end_time, :course_code, :capacity, :waitlist_capacity, :status, :room, :instructor_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description , class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :weekday_one %>
    <%= form.select :weekday_one, options_for_select(Course.weekday_ones.map {|key, value| [key.titleize, Course.weekday_ones.key(value)]}, @course.weekday_one) , {},{class: "form-control"}%>
  </div>

  <div class="form-group">
    <%= form.label :weekday_two %>
    <%= form.select :weekday_two, options_for_select(Course.weekday_twos.map {|key, value| [key.titleize, Course.weekday_twos.key(value)]}, @course.weekday_two) ,  {include_blank: true}, {class: "form-control"}%>
  </div>

  <div class="form-group">
    <%= form.label :start_time %>
    <%= form.text_field :start_time , class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :end_time %>
    <%= form.text_field :end_time , class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :course_code %>
    <%= form.text_field :course_code , class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :capacity %>
    <%= form.number_field :capacity , class:"form-control"%>
  </div>
  
  <div class="form-group">
    <%= form.label :waitlist_capacity %>
    <%= form.number_field :waitlist_capacity , class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :status, hidden: true%>
    <%= form.select :status, options_for_select(Course.statuses.map {|key, value| [key.titleize, Course.statuses.key(value)]}, @course.status) , {}, {include_blank: false, hidden: true, class:"form-control"}%>
  </div>

  <div class="form-group">
    <%= form.label :room %>
    <%= form.text_field :room , class:"form-control"%>
  </div>
  <% if is_admin? %>
  <div class="form-group">
    <%= form.label :instructor_id, "Instructor name" %>
    <%= form.select :instructor_id, options_for_select(Instructor.all.map{|ins| [ins.user.name, ins.id]}) ,{}, {include_blank: false, class:"form-control"}%>
  </div>
  <% end %>
                <br/>
                
  <div class="actions">
    <%= form.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course , class: 'btn btn-primary' %> |
<%= link_to 'Back', home_index_path , class: 'btn btn-primary' %>

app/views/courses/enrolled_students.html.erb
<p id="notice"><%= notice %></p>

<h1><% if @course_name %> <%= @course_name %> <%end%> Enrollments</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrolled_students.each do |enrolled| %>
      <tr>
        <td><%= enrolled.student.user.name %></td>
        <td><%= enrolled.student.user.email %></td>
        <td><%= link_to 'Drop', enrolled, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Enroll Students', show_enroll_course_for_student_path(@course), class: 'btn btn-primary'%> 
<%= link_to 'Back', :back , class: 'btn btn-primary' %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>
<% if !is_student? %>
<%= link_to 'New Course', new_course_path, class: 'btn btn-primary'  %>
<%end%>

<%= link_to 'Back', home_index_path , class: 'btn btn-primary' %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Instructor name</th>
      <th>Weekday one</th>
      <th>Weekday two</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Course code</th>
      <th>Capacity</th>
      <th>Waitlist Capacity</th>
      <th>Status</th>
      <th>Room</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td ><%= course.name %></td>
        <td><%= course.instructor.user.name %></td>
        <td><%= course.weekday_one %></td>
        <td><%= course.weekday_two %></td>
        <td><%= course.start_time %></td>
        <td><%= course.end_time %></td>
        <td><%= course.course_code %></td>
        <td><%= course.capacity %></td>
        <td><%= course.waitlist_capacity %></td>
        <td>
        <% if course.status == "open"%>
        <span class="btn btn-success btn-sm">Open</span>
        <% elsif course.status == "closed"%>
        <span class="btn btn-danger btn-sm">Closed</span>
        <% elsif course.status == "waitlist"%>
        <span class="btn btn-warning btn-sm">Waitlist</span>
        <% end %>        
        </td>
        <td><%= course.room %></td>
        <td><%= link_to 'Show', course,  class: 'btn btn-secondary btn-sm'%></td>
        <% if is_student? %>
          <%if Enrollment.find_by(:course_id => course.id, :student_id => get_cur_student.id)%>
            <td><%= link_to 'Drop Enrollment', enrollment_path(Enrollment.find_by(:course_id => course.id, :student_id => get_cur_student.id)), method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger btn-sm'%></td>
          <%elsif course.status == "open"%>
            <td><%= link_to 'Enroll', enroll_course_path(course.id), data: { confirm: 'Are you sure?' } , class: 'btn btn-primary btn-sm'%></td>
          <%elsif Waitlist.find_by(:course_id => course.id, :student_id => get_cur_student.id)%>
            <td><%= link_to 'Drop Waitlist', waitlist_path(Waitlist.find_by(:course_id => course.id, :student_id => get_cur_student.id)), method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger btn-sm'%></td>
          <%elsif course.status == "waitlist"%>
            <td><%= link_to 'Waitlist', waitlist_course_path(course.id), data: { confirm: 'Are you sure?' } , class: 'btn btn-primary btn-sm'%></td>
        <%end%>
        
        <% elsif is_instructor? && course.instructor_id == @instructor_id %>
          <td><%= link_to 'Enrolled', enrolled_students_path(course), class: 'btn btn-primary btn-sm'%> </td>
          <td><%= link_to 'Waitlisted', waitlisted_students_path(course), class: 'btn btn-primary btn-sm'%> </td>
          <td><%= link_to 'Edit', edit_course_path(course) , class: 'btn btn-warning btn-sm'%></td>
          <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger btn-sm'%></td>
          
        <% elsif is_admin? %>
          <td><%= link_to 'Enrolled', enrolled_students_path(course), class: 'btn btn-primary btn-sm'%> </td>
          <td><%= link_to 'Waitlisted', waitlisted_students_path(course), class: 'btn btn-primary btn-sm'%> </td>
          <td><%= link_to 'Edit', edit_course_path(course) , class: 'btn btn-warning btn-sm'%></td>
          <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger btn-sm'%></td>
        <% end %>
      </tr>
      
    <% end %>
  </tbody>
</table>

<br>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path , class: 'btn btn-primary' %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Instructor name:</strong>
  <%= @course.instructor.user.name %>
</p>

<p>
  <strong>Weekday one:</strong>
  <%= @course.weekday_one %>
</p>

<p>
  <strong>Weekday two:</strong>
  <%= @course.weekday_two %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @course.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @course.end_time %>
</p>

<p>
  <strong>Course code:</strong>
  <%= @course.course_code %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @course.capacity %>
</p>

<p>
  <strong>Status:</strong>
  <%= @course.status %>
</p>

<p>
  <strong>Room:</strong>
  <%= @course.room %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @course.instructor_id %>
</p>

<%if is_admin? || (is_instructor? && @course.instructor_id == @instructor_id)%>

    <%= link_to 'Enroll Students', show_enroll_course_for_student_path(@course), class: 'btn btn-primary'%> 
    <%= link_to 'Enrolled Students', enrolled_students_path(@course), class: 'btn btn-primary' %> 

    <%= link_to 'Waitlist Students', show_waitlist_course_for_student_path(@course), class: 'btn btn-primary'%> 
    <%= link_to 'Waitlisted Students', waitlisted_students_path(@course) , class: 'btn btn-primary'%> 
    <%= link_to 'Edit', edit_course_path(@course) , class: 'btn btn-primary'%> 
    <%= link_to 'Delete',  @course, method: :delete , class: 'btn btn-danger'%> 
<%end%>

<%= link_to 'Back', courses_path, class: 'btn btn-primary' %>

app/views/courses/waitlisted_students.html.erb
<p id="notice"><%= notice %></p>

<h1><% if @course_name %> <%= @course_name %> <%end%> Waitlists</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waitlisted_students.each do |waitlisted| %>
      <tr>
        <td><%= waitlisted.student.user.name %></td>
        <td><%= waitlisted.student.user.email %></td>
        <td><%= link_to 'Drop', waitlisted, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-primary btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Waitlist Students', show_waitlist_course_for_student_path(@course), class: 'btn btn-primary'%> 
<%= link_to 'Back', courses_path , class: 'btn btn-primary' %>